[phases.setup]
nixPkgs = [
  "php83",
  "php83Extensions.redis",
  "php83Extensions.pdo_pgsql",
  "php83Extensions.mbstring",
  "php83Extensions.exif",
  "php83Extensions.fileinfo",
  "php83Extensions.bcmath",
  "php83Extensions.intl",
  "php83Extensions.zip",
  "composer",
  "nodejs_20",
  "npm"
]

[phases.build]
cmds = [
  # install dependency Laravel & React
  "composer install --no-dev --optimize-autoloader",
  "npm install --include=optional",
  "npm rebuild lightningcss --force",
  "npm rebuild rollup --force",
  "export ROLLUP_USE_NODE_JS=1 && npm run build"
]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=${PORT:-8000}"
